version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

  pre_build:
    commands:
      - echo "Nothing to do in the pre_build phase..."

  build:
    commands:
      - npm run build

artifacts:
  files:
    - "dist/**/*"

cache:
  paths:
    - "node_modules"

post_build:
  commands:
    - mv dist /var/www/html

   
